### ISSUE TITLE
Upgrad Nunjucks to version: "nunjucks": ">=3.2.4"

### ISSUE THREAD

**Issue by jeicken** [acrontum/boats-utils#5]
Impact
In Nunjucks versions prior to version 3.2.4, it was possible to bypass the restrictions which are provided by the autoescape functionality. If there are two user-controlled parameters on the same line used in the views, it was possible to inject cross site scripting payloads using the backslash \ character.

Example
If the user-controlled parameters were used in the views similar to the following:

<script>
let testObject = { lang: '{{ lang }}', place: '{{ place }}' };
</script>
It is possible to inject XSS payload using the below parameters:

https://<application-url>/?lang=jp\&place=};alert(document.domain)//
Patches
The issue was patched in version 3.2.4.

References
https://bugzilla.mozilla.org/show_bug.cgi?id=1825980

**Comment by p-mcgowan** [comment]
issue is with boats - audit fix downgrades boats to 2.x to resolve the nunjucks error, but the tests fail because the feature required to support boats utils didn't exist then.

`npm audit --omit=dev` shows no prod audit issues (boats is only used during testing), so when projects `npm i` boats-utils they won't have an issue.

**Comment by p-mcgowan** [comment]
closing as isn't bundled in prod and PR to resolve opened
